### ISSUE TITLE
CDK version conflict?

### ISSUE THREAD

**Issue by harveyjc2001** [aws-samples/amazon-cognito-example-for-external-idp#1]
When running the deploy script, I see the following error:

CDK CLI can only be used with apps created by CDK >= 0.36.0

Was this built with a prior version of CDK that is incompatible? Tried to downgrade my version of CDK manually, but couldn't quite figure out how to do that.

**Comment by eranation** [comment]
Taking a look right now, thanks for letting me know!

**Comment by eranation** [comment]
@harveyjc2001 I'm updating the code to the latest CDK, there were a couple of breaking changes :) (https://github.com/awslabs/aws-cdk/releases) so my apologies for the delay, I want to test a few times to make sure everything works as before. Sorry again and thanks for reporting it! I'll also add more helpers (e.g. installing all npm dependencies in one go, also adding incremental tsc build etc) I hope to push an update sometime later today. Thanks for your patience!

**Comment by eranation** [comment]
@harveyjc2001 I updated to the latest CDK as well as made changes so that it will lock to that version (I'll update CDK periodically but this will ensure the global cdk won't break the existing code). I also made some changes to make it much simpler to setup and deploy, please let me know if there are still any issues!
