### ISSUE TITLE
External IDP authentication process

### ISSUE THREAD

**Issue by newtoworld999** [aws-samples/amazon-cognito-example-for-external-idp#22]
Hi
I have integrated cognito with external IDP using OIDC. In the ALB i mentioned the application(A) url to get authenticated to the cognito user pool which is integrated with external IDP. Once the user is authenticated when will cognito reachout to the external IDP again? As my app(A) is hosted as a linkout(sso enabled with cognito) and already session is created by IDP. The user has facility to change the some attributes once logged in  want to know how can i get the new user attributes which are different from the one they got after logged in 
ex: user logged in to some other portal and then clicks App A(hosted in aws integrated with cognito and external idp)
attributes a,b,c, are passed to backend app through cognito and then through ALB.
if user changes the attribute C how can the new attribute information be passed to the backend app in aws?

**Comment by eranation** [comment]
Due to the stateless nature of OIDC, once the token is issued its valid until its expiration date. If you change something in your IdP, you should plan for some time for it to "propagate". e.g. for tokens to expire so that users are pointed to the IdP again to re-authenticate. You can combine calls to AdminGlobalSignOut as well as with [custom expiration times](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-cognito-user-pools-supports-customization-of-token-expiration/#:~:text=Amazon%20Cognito%20User%20Pools%20now%20enables%20customers%20to%20choose%20how,as%20long%20as%20ten%20years.) to force users to sign out and re-authenticate. In this repo's example by the way, we save the timestamp of the last time the user has performed global sign out, and will immediately force users to re-authenticate. You can use a similar technique to force a user to re-authenticate via the IdP, e.g. for example if they changed a department or role or left the company etc, and you want it to take effect immediately. See [here](https://github.com/aws-samples/amazon-cognito-example-for-external-idp/search?q=forceSignOutHandler) for how it's used in the demo

**Comment by eranation** [comment]
Closing for now, but please feel free to reopen if you still have an issue or question.
